---
ID: "a0fee901-ca53-4a10-a210-6867212f871e"
Parent: "187b16a6-32e8-4ca5-8043-032978f94a4f"
Template: "187b16a6-32e8-4ca5-8043-032978f94a4f"
Path: /sitecore/templates/Feature/Sagittarius/Sagittarius Base Components/Rendering Parameters/Hero/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "38a6ddfa-bac1-456e-a557-7ca607d6889a"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UXounhYtFQ
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230702T070449Z
