---
ID: "477584ce-c7bd-46f4-a478-7917d6ad95fb"
Parent: "b6e0fc1b-248c-4f78-b03c-944454869f6e"
Template: "b6e0fc1b-248c-4f78-b03c-944454869f6e"
Path: /sitecore/templates/Feature/Sagittarius/Sagittarius Base Components/SponsorList/__Standard Values
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20220520T143324Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\xmc-e2e-admin@sitecore.com
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\xmc-e2e-admin@sitecore.com
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "67d5b30f-cd11-4eab-9703-1d5f4591a446"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UXounhYtFQ
    - ID: "d654a51c-b4ed-4dd4-8c83-fb20718a2535"
      Hint: Category
      Value: $name
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230702T070450Z
