---
ID: "dcfc39de-6a1c-4f36-82d7-f12dd73e0cfb"
Parent: "ae174a90-995a-4faf-9739-fc3c9344f48b"
Template: "ae174a90-995a-4faf-9739-fc3c9344f48b"
Path: /sitecore/templates/Feature/Sagittarius/Sagittarius Base Components/Rendering Parameters/CTA/__Standard Values
SharedFields:
- ID: "ca9b9f52-4fb0-4f87-a79f-24dea62cda65"
  Hint: __Default workflow
  Value: "{6C59AE29-D0A1-4B77-9305-0ABAB21D5FE5}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "d2e651d9-3a4c-464e-8775-6166b0773ff6"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\UXounhYtFQ
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20230702T070449Z
